import axios from 'axios';
import { env } from '../config/env';
import { logger } from '../utils/logger';
import pool from '../config/database';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ImageGenerateInput {
    post_text: string;
    topic: string;
    provider?: 'pollinations' | 'gemini';
    seed?: number;
    draft_id?: string; // If provided, automatically updates the draft with the image
}

export interface ImageGenerateResult {
    image_b64: string;
    format: string;
    width: number;
    height: number;
    provider: string;
    prompt_used: string;
    processing_time_ms: number;
    draft_updated: boolean;
}

// ─── Service ─────────────────────────────────────────────────────────────────

export const imageService = {
    /**
     * Calls the AI service to generate an image for a post,
     * then optionally persists the result to the draft's metadata column.
     */
    async generateImage(
        input: ImageGenerateInput,
        userId: string,
    ): Promise<ImageGenerateResult> {
        const aiServiceUrl = env.AI_SERVICE_URL;
        const aiServiceKey = env.AI_SERVICE_KEY;

        logger.info('Image generation requested', {
            userId,
            provider: input.provider || 'pollinations',
            topic: input.topic.substring(0, 50),
            draftId: input.draft_id,
        });

        // Call the AI Service
        const { data } = await axios.post(
            `${aiServiceUrl}/generate-image`,
            {
                post_text: input.post_text,
                topic: input.topic,
                provider: input.provider || 'pollinations',
                seed: input.seed ?? 42,
            },
            {
                headers: { 'X-API-Key': aiServiceKey },
                timeout: 120_000, // Pollinations can take up to 90s under load
            }
        );

        logger.info('Image generated by AI service', {
            provider: data.provider,
            processingMs: data.processing_time_ms,
        });

        let draftUpdated = false;

        // If a draft_id was supplied, persist image into draft.metadata
        if (input.draft_id) {
            try {
                // Fetch current metadata first (JSONB merge pattern)
                const existing = await pool.query(
                    `SELECT metadata FROM drafts WHERE id = $1 AND user_id = $2`,
                    [input.draft_id, userId]
                );

                if (existing.rows.length > 0) {
                    const currentMeta = existing.rows[0].metadata || {};
                    const updatedMeta = {
                        ...currentMeta,
                        image_b64: data.image_b64,
                        image_format: data.format,
                        image_provider: data.provider,
                        image_prompt: data.prompt_used,
                        image_generated_at: new Date().toISOString(),
                    };

                    await pool.query(
                        `UPDATE drafts SET metadata = $1, updated_at = NOW() WHERE id = $2 AND user_id = $3`,
                        [JSON.stringify(updatedMeta), input.draft_id, userId]
                    );

                    draftUpdated = true;
                    logger.info('Draft metadata updated with image', { draftId: input.draft_id });
                }
            } catch (err: any) {
                // Non-fatal — image is still returned to frontend even if DB update fails
                logger.warn('Failed to persist image to draft metadata', { error: err.message, draftId: input.draft_id });
            }
        }

        return {
            image_b64: data.image_b64,
            format: data.format,
            width: data.width,
            height: data.height,
            provider: data.provider,
            prompt_used: data.prompt_used,
            processing_time_ms: data.processing_time_ms,
            draft_updated: draftUpdated,
        };
    },
};
